#!/usr/bin/env sh
set -eu

: "${DB_USERNAME:?}"
: "${DB_PASSWORD:?}"
: "${DB_HOST:?}"
: "${DB_PORT:?}"
: "${DB_DATABASE:?}"

atlas schema apply --var "schema_name=${DB_DATABASE}" --env production --auto-approve
