#!/usr/bin/env php
<?php

declare(strict_types=1);

use Support\Path\Path;
use Tempest\Console\ConsoleApplication;

require_once getcwd() . '/vendor/autoload.php';

Path::setRoot(__DIR__);

ConsoleApplication::boot()->run();
