[tasks.format]
description = "フォーマット修正をする"
run = "bun run format"

[tasks."format:check"]
description = "フォーマットチェックをする"
run = "bun run format:check"

[tasks."compile:all"]
description = "oas を生成する"
run = [{ tasks = ["compile:viewer", "compile:admin"] }]

[tasks."compile:viewer"]
description = "Viewer 用 oas を生成する"
run = "bun run compile:viewer"

[tasks."compile:viewer:watch"]
description = "Viewer 用 oas を生成する(watch)"
run = "bun run compile:viewer:watch"

[tasks."compile:admin"]
description = "Admin 用 oas を生成する"
run = "bun run compile:admin"

[tasks."compile:admin:watch"]
description = "Admin 用 oas を生成する(watch)"
run = "bun run compile:admin:watch"

[tasks.re-compile]
description = "oas を生成し直す"
run = '''
rm -rf generated/oas
mise run compile:all
'''
