services:
  node:
    image: isekai-terrarium:22
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      NODE_EXTRA_CA_CERTS: /usr/share/ca-certificates/rootCA.pem
    tty: true
    ports:
      - 3000:4321
    volumes:
      - ./src:/app
    extra_hosts:
      - local.api.terrarium.isekaijoucho.fan:host-gateway
      - local.admin.terrarium.isekaijoucho.fan:host-gateway
