name: Admin QA

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    branches:
      - dev

env:
  MISE_ENV: ci

jobs:
  diff:
    name: Generated Code Diff Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            src/node_modules
            src/admin/node_modules
          key: admin-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run pnpm:install

      - name: Check generate code has diff
        run: mise run admin:generate

  lint:
    name: ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            src/node_modules
            src/admin/node_modules
          key: admin-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run pnpm:install

      - name: Run ESLint
        run: mise run admin:lint

  style:
    name: Stylelint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            src/node_modules
            src/admin/node_modules
          key: admin-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run pnpm:install

      - name: Run Stylelint
        run: mise run admin:style

      # - name: Run Build
      #   run: bun run build
