name: Admin Client QA

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    branches:
      - dev

env:
  MISE_ENV: ci

jobs:
  diff:
    name: Generated Code Diff Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: src/admin/node_modules
          key: node-modules-${{ hashFiles('**/bun.lock') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run bun:install

      - name: Check generate code has diff
        run: mise run generate:client

  lint:
    name: ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: src/admin/node_modules
          key: node-modules-${{ hashFiles('**/bun.lock') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run bun:install

      - name: Run ESLint
        run: mise run lint

  style:
    name: Stylelint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: src/admin/node_modules
          key: node-modules-${{ hashFiles('**/bun.lock') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run bun:install

      - name: Run Stylelint
        run: mise run style

      # - name: Run Build
      #   run: bun run build
