name: Arkitect

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  check:
    needs: setup

    name: Arkitect

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Cache docker image
        id: cache-server-docker-image
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-server-docker-cache }}
          key: ${{ needs.setup.outputs.key-server-docker-cache }}

      - name: Load image
        if: steps.cache-server-docker-image.outputs.cache-hit == 'true'
        run: gunzip -c ${{ needs.setup.outputs.server-docker-cache }} | docker load

      - name: Run Container
        run: docker compose up -d php

      - name: Cache composer
        id: cache-composer
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-vendor-cache }}
          key: ${{ needs.setup.outputs.key-composer-cache }}

      - name: Move vendor
        if: steps.cache-composer.outputs.cache-hit == 'true'
        run: tar -xzf ${{ needs.setup.outputs.vendor-cache }}

      - name: Dump autoload
        run: docker exec ${{ needs.setup.outputs.server-container }} composer dump-autoload

      - name: Check Layer
        run: docker exec ${{ needs.setup.outputs.server-container }} composer arkitect
