name: Client CI

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    branches:
      - dev

env:
  WORKING_DIR: ./src/client
  MISE_ENV: ci

jobs:
  check:
    name: Client CI (Node ${{ matrix.node-versions }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-versions: ["22"]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Setup mise config
        run: cp mise.ci.toml mise.local.toml

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ${{ env.WORKING_DIR }}/node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run ci:npm:install

      - name: Check generate code has diff
        run: |
          mise run ci:generate:client
          if [ -n "$(git status --porcelain)" ]; then
            echo "自動生成コードに差分があります"
            git status
            exit 1
          fi

      - name: Run ESLint
        run: mise run ci:lint

      - name: Run Stylelint
        run: mise run ci:style

      # - name: Run Build
      #   working-directory: ${{ env.WORKING_DIR }}
      #   run: npm run build
