name: Client QA

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    branches:
      - dev

env:
  MISE_ENV: qa

jobs:
  check:
    name: Client QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Setup mise
        uses: jdx/mise-action@v3

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: src/client/node_modules
          key: node-modules-${{ hashFiles('**/bun.lock') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run bun:install

      - name: Check generate code has diff
        run: mise run generate:client

      - name: Run ESLint
        run: mise run lint

      - name: Run Stylelint
        run: mise run style

      # - name: Run Build
      #   run: bun run build
