name: Contracts QA

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  format:
    name: Format Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            src/node_modules
            src/contracts/node_modules
          key: contracts-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run pnpm:install

      - name: Check format
        run: mise run contract:format:check

  diff:
    name: Generated Code Diff Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            src/node_modules
            src/contracts/node_modules
          key: contracts-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run pnpm:install

      - name: Check generate code has diff
        run: |
          mise run contract:compile:all
          if [ -n "$(git status --porcelain | grep generated)" ]; then
            echo "自動生成コードに差分があります"
            git status
            exit 1
          fi
