name: Deptrac

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  setup-php:
    uses: ./.github/workflows/setup-php.yaml

  check:
    needs: setup-php

    name: Deptrac (PHP ${{ needs.setup-php.outputs.php-version }})

    runs-on: ubuntu-latest

    steps:
      - name: Check Layer
        run: |
          echo 'Check Layer'
          cd src
          composer deptrac
