name: EasyCodingStandard

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  lint:
    needs: setup

    name: EasyCodingStandard

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Cache docker image
        id: cache-docker-image
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.docker-cache-path }}
          key: ${{ needs.setup.outputs.docker-cache-key }}

      - name: Load image
        if: steps.cache-docker-image.outputs.cache-hit == 'true'
        run: gunzip -c ${{ needs.setup.outputs.docker-cache }} | docker load

      - name: Run Container
        run: docker compose up -d php

      - name: Cache composer
        id: cache-composer
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.vendor-cache-path }}
          key: ${{ needs.setup.outputs.composer-cache-key }}

      - name: Move vendor
        if: steps.cache-composer.outputs.cache-hit == 'true'
        run: tar -xzf ${{ needs.setup.outputs.vendor-cache }}

      - name: Run ecs
        run: docker exec ${{ needs.setup.outputs.container }} composer ecs
