name: ESLint and build

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  analyse:
    needs: setup

    name: ESLint and build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Cache docker image
        id: cache-server-docker-image
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-server-docker-cache }}
          key: ${{ needs.setup.outputs.key-server-docker-cache }}

      - name: Load image
        if: steps.cache-server-docker-image.outputs.cache-hit == 'true'
        run: gunzip -c ${{ needs.setup.outputs.server-docker-cache }} | docker load

      - name: Run Container
        run: docker compose up -d php

      - name: Cache npm
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-npm-cache }}
          key: ${{ needs.setup.outputs.key-npm-cache }}

      - name: Move npm
        if: steps.cache-npm.outputs.cache-hit == 'true'
        run: tar -xzf ${{ needs.setup.outputs.npm-cache }}

      - name: Run ESLint
        run: docker exec ${{ needs.setup.outputs.server-container }} npm run lint

      - name: Run Build
        run: docker exec ${{ needs.setup.outputs.server-container }} npm run build
