name: ESLint and build

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  setup-node:
    uses: ./.github/workflows/setup-node.yaml

  analyse:
    needs: setup-node

    name: ESLint and build (Node ${{ needs.setup-node.outputs.version }})

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup-node.outputs.version }}

      - name: npm cache
        id: npm_cache
        uses: actions/cache@v4
        with:
          path: ./src/node_modules
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-package-

      - name: Run ESLint
        run: |
          cd src
          npm run lint

      - name: Run Build
        run: |
          cd src
          npm run build
