name: PHPStan

on: pull_request

jobs:
  analyse:
    name: PHPStan (PHP ${{ matrix.php-versions }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.3"]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Composer cache
        id: composer_cache
        uses: actions/cache@v4
        with:
          path: ./src/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install packages
        shell: bash
        if: steps.composer_cache.outputs.cache-hit != 'true'
        run: |
          echo 'Install packages'
          cd src
          composer install -n --prefer-dist

      - name: Run PHPStan
        run: |
          cd src
          composer stan
