name: PHPStan

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  analyse:
    needs: setup

    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Cache docker image
        id: cache-docker-image
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-docker-cache }}
          key: ${{ needs.setup.outputs.key-docker-cache }}

      - name: Load image
        if: steps.cache-docker-image.outputs.cache-hit == 'true'
        run: gunzip -c ${{ needs.setup.outputs.docker-cache }} | docker load

      - name: Run Container
        run: docker compose up -d php

      - name: Cache composer
        id: cache-composer
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-vendor-cache }}
          key: ${{ needs.setup.outputs.key-composer-cache }}

      - name: Move vendor
        if: steps.cache-composer.outputs.cache-hit == 'true'
        run: tar -xzf ${{ needs.setup.outputs.vendor-cache }}

      - name: Cache gRPC
        id: cache-grpc
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-grpc-cache }}
          key: ${{ needs.setup.outputs.key-grpc-cache }}

      - name: Move generate code
        if: steps.cache-grpc.outputs.cache-hit == 'true'
        run: tar -xzf ${{ needs.setup.outputs.grpc-cache }}

      - name: Dump autoload
        run: docker exec ${{ needs.setup.outputs.container }} composer dump-autoload

      - name: Run PHPStan
        run: docker exec ${{ needs.setup.outputs.container }} composer phpstan
