name: PHPUnit

on: [pull_request, push]

jobs:
  setup-php:
    uses: ./.github/workflows/setup-php.yaml

  setup-node:
    uses: ./.github/workflows/setup-node.yaml

  test:
    needs:
      - setup-php
      - setup-node

    name: PHPUnit (PHP ${{ needs.setup-php.outputs.php-version }}/Node ${{ needs.setup-node.outputs.node-version }})

    runs-on: ubuntu-latest

    steps:
      - name: Create Database
        shell: bash
        run: |
          cd src
          mkdir -p database
          touch database/database.sqlite

      - name: Setup env
        shell: bash
        run: |
          cd src
          cp .env.testing.example .env.testing
          php artisan key:generate --env=testing

      - name: Build
        shell: bash
        run: |
          cd src
          npm run build

      - name: Migrate
        shell: bash
        run: |
          cd src
          php artisan migrate --env=testing

      - name: Run PHPUnit
        run: |
          cd src
          composer test-all
