name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  test:
    needs: setup

    name: PHPUnit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Cache docker image
        id: cache-server-docker-image
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-server-docker-cache }}
          key: ${{ needs.setup.outputs.key-server-docker-cache }}

      - name: Load image
        if: steps.cache-server-docker-image.outputs.cache-hit == 'true'
        run: gunzip -c ${{ needs.setup.outputs.server-docker-cache }} | docker load

      - name: Run Container
        run: docker compose up -d php

      - name: Cache composer
        id: cache-composer
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-vendor-cache }}
          key: ${{ needs.setup.outputs.key-composer-cache }}

      - name: Move vendor
        if: steps.cache-composer.outputs.cache-hit == 'true'
        run: tar -xzf ${{ needs.setup.outputs.vendor-cache }}

      - name: Cache database
        id: cache-database
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.path-database-cache }}
          key: ${{ needs.setup.outputs.key-database-cache }}

      - name: Move database
        if: steps.cache-database.outputs.cache-hit == 'true'
        run: tar -xzf ${{ needs.setup.outputs.database-cache }}

      - name: Setup env
        run: |
          cp src/server/.env.testing.example src/server/.env.testing
          docker exec ${{ needs.setup.outputs.server-container }} php artisan key:generate --env=testing

      - name: Dump autoload
        run: docker exec ${{ needs.setup.outputs.server-container }} composer dump-autoload

      - name: Run PHPUnit
        run: docker exec ${{ needs.setup.outputs.server-container }} composer test-unit
