name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  setup-php:
    uses: ./.github/workflows/setup-php.yaml

  setup-node:
    uses: ./.github/workflows/setup-node.yaml

  test:
    needs:
      - setup-php
      - setup-node

    name: PHPUnit (PHP ${{ needs.setup-php.outputs.version }}/Node ${{ needs.setup-node.outputs.version }})

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ needs.setup-php.outputs.version }}
          extensions: grpc
          tools: composer

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup-node.outputs.version }}

      - name: Composer cache
        id: composer_cache
        uses: actions/cache@v4
        with:
          path: ./src/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: npm cache
        id: npm_cache
        uses: actions/cache@v4
        with:
          path: ./src/node_modules
          key: ${{ runner.os }}-package-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-package-

      - name: Create Database
        run: |
          cd src
          mkdir -p database
          touch database/database.sqlite

      - name: Setup env
        run: |
          cd src
          cp .env.testing.example .env.testing
          php artisan key:generate --env=testing

      - name: Build
        run: |
          cd src
          npm run build

      - name: Migrate
        run: |
          cd src
          php artisan migrate --env=testing

      - name: Run PHPUnit
        run: |
          cd src
          composer test-all
