name: setup server

on:
  workflow_call:
    outputs:
      path-server-docker-cache:
        value: ${{ jobs.setup.outputs.path-server-docker-cache }}
      key-server-docker-cache:
        value: ${{ jobs.setup.outputs.key-server-docker-cache }}
      server-docker-cache:
        value: ${{ jobs.setup.outputs.server-docker-cache }}
      server-container:
        value: ${{ jobs.setup.outputs.server-container }}
      path-vendor-cache:
        value: ${{ jobs.setup.outputs.path-vendor-cache }}
      key-composer-cache:
        value: ${{ jobs.setup.outputs.key-composer-cache }}
      vendor-cache:
        value: ${{ jobs.setup.outputs.vendor-cache }}
      path-database-cache:
       value: ${{ jobs.setup.outputs.path-database-cache }}
      key-database-cache:
        value: ${{ jobs.setup.outputs.key-database-cache }}
      database-cache:
        value: ${{ jobs.setup.outputs.database-cache }}

jobs:
  setup:
    name: Setup server

    runs-on: ubuntu-latest

    outputs:
      path-server-docker-cache: ${{ steps.define-variables.outputs.PATH_SERVER_DOCKER_CACHE }}
      key-server-docker-cache: ${{ steps.define-variables.outputs.KEY_SERVER_DOCKER_CACHE }}
      server-docker-cache: ${{ steps.define-variables.outputs.SERVER_DOCKER_CACHE }}
      server-container: ${{ steps.define-variables.outputs.SERVER_CONTAINER }}
      path-vendor-cache: ${{ steps.define-variables.outputs.PATH_VENDOR_CACHE }}
      key-composer-cache: ${{ steps.define-variables.outputs.KEY_COMPOSER_CACHE }}
      vendor-cache: ${{ steps.define-variables.outputs.VENDOR_CACHE }}
      path-database-cache: ${{ steps.define-variables.outputs.PATH_DATABASE_CACHE }}
      key-database-cache: ${{ steps.define-variables.outputs.KEY_DATABASE_CACHE }}
      database-cache: ${{ steps.define-variables.outputs.DATABASE_CACHE }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Define variables
        id: define-variables
        run: |
          ROOT_CACHE="/tmp/cache"
          # Docker 関連(Server)
          PATH_SERVER_DOCKER_CACHE="${ROOT_CACHE}/docker/server"
          HASH_SERVER_DOCKERFILE="${{ hashFiles('./docker/php/Dockerfile', './docker/php/Dockerfile.ci') }}"
          KEY_SERVER_DOCKER_CACHE="docker-server-${HASH_SERVER_DOCKERFILE}"
          SERVER_DOCKER_CACHE="${PATH_SERVER_DOCKER_CACHE}/${HASH_SERVER_DOCKERFILE}.tar.gz"
          SERVER_CONTAINER="isekai-journey-admin-php"
          echo "PATH_SERVER_DOCKER_CACHE=${PATH_SERVER_DOCKER_CACHE}" >> $GITHUB_OUTPUT
          echo "KEY_SERVER_DOCKER_CACHE=${KEY_SERVER_DOCKER_CACHE}" >> $GITHUB_OUTPUT
          echo "SERVER_DOCKER_CACHE=${SERVER_DOCKER_CACHE}" >> $GITHUB_OUTPUT
          echo "SERVER_CONTAINER=${SERVER_CONTAINER}" >> $GITHUB_OUTPUT
          # Composer 関連
          PATH_VENDOR_CACHE="${ROOT_CACHE}/vendor"
          HASH_COMPOSER_LOCK="${{ hashFiles('./src/server/composer.lock') }}"
          KEY_COMPOSER_CACHE="composer-${HASH_COMPOSER_LOCK}"
          VENDOR_CACHE="${PATH_VENDOR_CACHE}/${KEY_COMPOSER_CACHE}.tar.gz"
          echo "PATH_VENDOR_CACHE=${PATH_VENDOR_CACHE}" >> $GITHUB_OUTPUT
          echo "KEY_COMPOSER_CACHE=${KEY_COMPOSER_CACHE}" >> $GITHUB_OUTPUT
          echo "VENDOR_CACHE=${VENDOR_CACHE}" >> $GITHUB_OUTPUT
          # テスト用 DB 関連
          PATH_DATABASE_CACHE="${ROOT_CACHE}/db"
          HASH_DATABASE="${{ hashFiles('./src/server/database/migrations/*.php') }}"
          KEY_DATABASE_CACHE="database-${HASH_DATABASE}"
          DATABASE_CACHE="${PATH_DATABASE_CACHE}/${KEY_DATABASE_CACHE}.tar.gz"
          echo "PATH_DATABASE_CACHE=${PATH_DATABASE_CACHE}" >> $GITHUB_OUTPUT
          echo "KEY_DATABASE_CACHE=${KEY_DATABASE_CACHE}" >> $GITHUB_OUTPUT
          echo "DATABASE_CACHE=${DATABASE_CACHE}" >> $GITHUB_OUTPUT

      - name: Cache server docker image
        id: cache-server-docker-image
        uses: actions/cache@v4
        with:
          path: ${{ steps.define-variables.outputs.PATH_SERVER_DOCKER_CACHE }}
          key: ${{ steps.define-variables.outputs.KEY_SERVER_DOCKER_CACHE }}

      - name: Login to Docker Hub
        if: steps.cache-server-docker-image.outputs.cache-hit != 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build server image
        if: steps.cache-server-docker-image.outputs.cache-hit != 'true'
        run: |
          docker build -t isekai-journey-admin-php:8.4 -f ./docker/php/Dockerfile.ci ./docker/php \
          --build-arg UID=`id -u` \
          --build-arg GID=`id -g` \
          --build-arg USERNAME=`id -un` \
          --build-arg GROUPNAME=`id -gn`
          mkdir -p ${{ steps.define-variables.outputs.PATH_SERVER_DOCKER_CACHE }}
          docker save isekai-journey-admin-php:8.4 | gzip > ${{ steps.define-variables.outputs.SERVER_DOCKER_CACHE }}

      - name: Load server image
        if: steps.cache-server-docker-image.outputs.cache-hit == 'true'
        run: gunzip -c ${{ steps.define-variables.outputs.SERVER_DOCKER_CACHE }} | docker load

      - name: Copy .env
        run: |
          cp src/server/.env.example src/server/.env
          cp src/server/.env.testing.example src/server/.env.testing

      - name: Run Container
        run: docker compose up -d php

      - name: Cache composer
        id: cache-composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.define-variables.outputs.PATH_VENDOR_CACHE }}
          key: ${{ steps.define-variables.outputs.KEY_COMPOSER_CACHE }}

      - name: Composer install
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: |
          docker exec ${{ steps.define-variables.outputs.SERVER_CONTAINER }} composer install -n --prefer-dist
          mkdir -p ${{ steps.define-variables.outputs.PATH_VENDOR_CACHE }}
          tar -czf ${{ steps.define-variables.outputs.VENDOR_CACHE }} src/server/vendor

      - name: Move vendor
        if: steps.cache-composer.outputs.cache-hit == 'true'
        run: tar -xzf ${{ steps.define-variables.outputs.VENDOR_CACHE }}

      - name: Check Generate code has diff
        run: |
          docker exec ${{ steps.define-variables.outputs.SERVER_CONTAINER }} ./gen-stub.sh
          if [ -n "$(git status --porcelain)" ]; then
            echo "自動生成コードに差分があります"
            git status
            exit 1
          fi

      - name: Cache database
        id: cache-database
        uses: actions/cache@v4
        with:
          path: ${{ steps.define-variables.outputs.PATH_DATABASE_CACHE }}
          key: ${{ steps.define-variables.outputs.KEY_DATABASE_CACHE }}

      - name: Migrate
        if: steps.cache-database.outputs.cache-hit != 'true'
        run: |
          touch src/server/database/database.sqlite
          docker exec ${{ steps.define-variables.outputs.SERVER_CONTAINER }} php artisan migrate --env=testing
          mkdir -p ${{ steps.define-variables.outputs.PATH_DATABASE_CACHE }}
          tar -czf ${{ steps.define-variables.outputs.DATABASE_CACHE }} src/server/database/database.sqlite
