name: Update Actions Versions

on:
  schedule:
    # 毎日 JST 9:00 (UTC 0:00)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  pinact:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup mise
        uses: ./.github/actions/setup-mise

      - name: Update action versions
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: pinact run --min-age 7 --update

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: auto/update-actions-version
          commit-message: 'ci: update pinned actions versions'
          title: 'ci: update pinned actions versions'
          body: |
            GitHub Actions で `pinact run --min-age 7 --update` を実行した差分です。
          delete-branch: true
