name: WIP Check By Title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  statuses: write

jobs:
  set-status:
    runs-on: ubuntu-latest

    steps:
      - name: Set status check to pending
        if: "contains(github.event.pull_request.title, '[WIP]')"
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
            --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "WIP Check",
              "state": "pending",
              "description": "❌ [WIP] をタイトルから削除するとマージできます"
            }'

      - name: Set status check to success
        if: "!contains(github.event.pull_request.title, '[WIP]')"
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
            --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "WIP Check",
              "state": "success",
              "description": "✅ マージできます"
            }'
